# pandas Fundamentals
McKinney Ch 5 (basics) + Ch 7 (data cleaning). Ch 6 has no exercises

In [2]:
import numpy as np
import pandas as pd

---
## Chapter 5 — pandas Basics

### Series

In [3]:
obj = pd.Series([4, 7, -5, 3])
obj
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2['a']
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [7]:
obj2[obj2 > 0] #only keep positive values
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [8]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

A series maps index values (left column) to actual data values
- similar to a dictionary
- dict = unformatted, array style listing

In [9]:
"b" in obj2
"e" in obj2

False

In [10]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [11]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [12]:
states = ["California", "Ohio", "Oregon", "Texas"] # California is not in sdata, so it will be NaN
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [13]:
pd.isna(obj4) #check if values are NaN
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [14]:
obj3 + obj4 #arithmethic between different indexes. NaN is like undefined

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [15]:
obj4.name = "population" #name the entire Series
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [16]:
obj
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan'] #adding an index
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame
dictionary of Series' with the same index

In [17]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003], 
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [18]:
frame.head() #show only first 5 rows
frame.tail(3) #show only last 3 rows

    state  year  pop
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [19]:
pd.DataFrame(data, columns=['year', 'state', 'pop']) #specify column order

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [20]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [21]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [22]:
frame2["state"] #returns Series of a single column
frame2.year #works the same way

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

### .loc vs .iloc
special attributes to select rows and columns from a DataFrame

In [23]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [24]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

iloc = uses integer
loc = uses labels (actual index values and column names)

### Index alignment in arithmetic

In [25]:
frame2["debt"] = 16.5
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [26]:
frame2["debt"] = np.arange (6.)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])
frame2["debt"] = val
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [36]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2
del frame2["eastern"]
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [37]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [38]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [39]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [40]:
pdata = {"Ohio": frame3["Ohio"][:-1], 
         "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

*slice notation*

[start:stop]
stop number is always excluded

In [ ]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3 #unlike Series, DataFrame doesn't have a name attribute

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [44]:
frame3.to_numpy()
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [46]:
obj = pd.Series(np.arange(3), index=['a', 'b', 'c'])
index = obj.index
index
index[1:]

Index(['b', 'c'], dtype='object')

In [47]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [49]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2
obj2.index is labels

True

Index are kinda like arrays

In [ ]:
frame3
frame3.columns
"Ohio" in frame3.columns #is Ohio in the columns of frame3
2003 in frame3.index #is 2003 in the index of frame3 (no)

False

In [54]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

### Reindexing

In [55]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [56]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) #reindexing to a new set of indexes
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [57]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [58]:
obj3.reindex(np.arange(6), method="ffill") #forward fill method for reindexing

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), 
                     index=['a', 'c', 'd'], 
                     columns=['Ohio', 'Texas', 'California'])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [60]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [62]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states) #reindex with a keyword

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [63]:
frame.reindex(states, axis="columns") #same way to do ^^ with axis keyword instead

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [65]:
frame.loc[["a", "d", "c"], ["California", "Texas"]] #reindexing with loc, changing both rows and columns at once

   California  Texas
a           2      1
d           8      7
c           5      4

---
### Exercises — Ch 5

**Build and index a vitals DataFrame**

Construct a DataFrame with columns `['patient_id', 'hr', 'spo2', 'temp']` and 10 rows of made-up values.
Use `.loc` to select rows where `hr > 100`. Use `.iloc` to select the first 3 rows and first 2 columns.
Confirm the results are what you expected.

**Index alignment**

Make two Series:
```
a = pd.Series([1, 2, 3], index=['a','b','c'])
b = pd.Series([10, 20], index=['b','c'])
```
Add them. Predict what happens to index `'a'` before running.

---
## Chapter 7 — Data Cleaning

### Missing data — dropna / fillna / isnull

In [28]:
# type code as you read — predict output before running

### Outlier detection and clip

In [29]:
# type code as you read — predict output before running

### pd.cut / pd.qcut

In [30]:
# type code as you read — predict output before running

### apply / map

In [31]:
# type code as you read — predict output before running

### pd.get_dummies

In [32]:
# type code as you read — predict output before running

---
### Exercises — Ch 7

**Missing vitals**

Build a DataFrame with columns `['hr', 'spo2', 'temp']` and 20 rows.
Randomly set ~15% of values to NaN using `rng.choice`.
Count missing values per column. Then fill `hr`/`spo2` with forward-fill and `temp` with the column mean.
Verify no NaNs remain.

**Outlier clip**

Given `spo2 = pd.Series([98, 102, 75, 99, -3, 95, 101, 88])`,
identify values outside physiologic range (70–100) using a boolean mask.
Replace them with NaN, then forward-fill.

**Binning HR into clinical labels**

Given `hr = pd.Series([55, 78, 105, 160, 190, 95, 130])`,
use `pd.cut` with `bins=[0, 60, 100, 160, 300]` and `labels=['brady','low-normal','normal','tachy']`.

**Dummy variables**

Given a DataFrame with a `'sex'` column containing `'M'`/`'F'` and a `'ga_group'` column with `'preterm'`/`'term'`,
use `pd.get_dummies` with `drop_first=True` and confirm the output shape.